#!/bin/sh
exit
source ~mgrastprod/.zshenv 

# $1   job_id
# $2   file_name
# $3   is_fastq    boolean
# $4   options_string
# $5   rna_only    boolean

if [ $3 -eq 1 ]; then
    create_job -j $1 -u $2 -f $2 -p $4 -q
else
    create_job -j $1 -u $2 -f $2 -p $4
fi

#if [ $5 -eq 1 ]; then
##    submit_stages -j $1 -o $4 -p 16s
#else
#    submit_stages -j $1 -o $4
#fi

#echo "create_job -j "$1" -u "$2" -f "$2"; submit_stages -j "$1";" | qsub -u jared -l nodes=1:ppn=1 -l walltime=0:120:00 -j oe -o /tmp -N $1.create_job -m n
