#!/usr/bin/env perl 

use strict;
use warnings;
no warnings('once');

use Pipeline;
use Pipeline_Conf;

use Getopt::Long;
use File::Copy;
umask 000;

my $stage_name="sims_to_abundance";
my $stage;
for my $s (@{$Pipeline_Conf::pipeline->{'default'}}) {
  $stage = $s if $s->{name} eq $stage_name; 
}
my $stage_id = $stage->{id};
my $revision = "0";
my $version  = $Pipeline_Conf::pipeline_version.".".$revision;

# options
my $job_num = "";
my $sims    = "";
my $mem_key = $Pipeline_Conf::memcache_key;
my $procs   = 2;
my $ver     = 0;
my $help    = 0;
my $options = GetOptions ("job=i"           => \$job_num,
			  "aa_sims_file:s"  => \$aa_sims_file,
			  "rna_sims_file:s" => \$rna_sims_file,
			  "procs:i"         => \$procs,
			  "mem_key:s"       => \$mem_key,
			  "version!"        => \$ver,
			  "help!"           => \$help
			 );
if ( $ver ) {
  print STDERR "$stage_name - $version - $stage_id\n";
  exit(0);
} elsif ( $help or !($job_num and $rna_sims_file and $aa_sims_file) ) {
  print STDERR "Usage: pipeline_$stage_name -j <job number> -a <aa sims file> -r <rna sims file> [ -m <memcache key> -p <# processors for sort, default $procs>]\n";
  exit(1);
}

my $log = Pipeline::logger($job_num);
$log->info("Starting $stage_name on job: $job_num");

unless (-e $aa_sims_file) {
  $log->error("file: $aa_sims_file does not exist");
  exit(1);
}

unless (-e $rna_sims_file) {
  $log->error("file: $rna_sims_file does not exist");
  exit(1);
}

# update jobcache stage status
Pipeline::update_stage_info($job_num, $stage_name, "running");

my $job_dir     = $Pipeline_Conf::global_job_dir."/".$job_num;
my $proc_dir    = $job_dir."/proc";
my $stage_dir   = $proc_dir."/".$stage_id.".".$stage_name;
my $results_dir = $job_dir."/".$Pipeline_Conf::results_dir;
my $run_dir     = $stage_dir;
my $hostname    = `hostname`;
chomp $hostname;

# create directories
if (-d $stage_dir) {
  my $t = time;
  $log->info("found $stage_dir, moving to $stage_dir.$t");
  move($stage_dir, $stage_dir.".".$t) or fail($log, "$!");
}
mkdir($stage_dir) or fail($log, "Could not mkdir: $stage_dir, $!");

# set cluster workspace dir (use local if large job)
my $work_dir = (($procs >= 4) && (-d $Pipeline_Conf::local_workspace)) ? $Pipeline_Conf::local_workspace : $Pipeline_Conf::cluster_workspace;
if (-d $work_dir) {
  $run_dir = "$work_dir/$job_num.$stage_id.$stage_name";
  if (-d $run_dir) {
    system("rm -rf $run_dir");
  }
  mkdir($run_dir) or fail($log, "Could not mkdir: $run_dir, $!");
  system("echo $hostname > $stage_dir/hostname");
}
$log->info("Running on host $hostname, using dir $run_dir");

my $sort_dir = (-d $Pipeline_Conf::local_tmp) ? $Pipeline_Conf::local_tmp : ((-d $Pipeline_Conf::cluster_tmp) ? $Pipeline_Conf::cluster_tmp : $run_dir);
my $prefix   = $stage_id.".".$stage_name;
my $err_file = $stage_dir."/".$prefix.".err";
my $message  = "$stage_name failed on job: $job_num, see $err_file for details.";

# process_rna_sims
system("process_rna_sims --in_sim $rna_sims_file --sort_dir $sort_dir --run_dir $run_dir --err_file $err_file --prefix $prefix --mem_host $Pipeline_Conf::memcache_host --mem_key $mem_key --procs $procs") or fail($log, "process_rna_sims: ".$message);

# cleanup
#move("$sims_file.sort", "$results_dir/$prefix.sims") or fail($log, "Failed copy: $prefix.sims.sort - $!");
#move("$sims_file.filter", "$results_dir/$prefix.sims.filter") or fail($log, "Failed copy: $prefix.sims.filter - $!");
#move("$run_dir/$prefix.expand.rna", "$results_dir/$prefix.expand.rna") or fail($log, "Failed copy: $prefix.expand.rna - $!");
#move("$run_dir/$prefix.expand.lca", "$results_dir/$prefix.expand.lca") or fail($log, "Failed copy: $prefix.expand.lca - $!");

#chmod 0666, "$results_dir/$prefix.sims"; 
#chmod 0666, "$results_dir/$prefix.sims.filter";
#chmod 0666, "$results_dir/$prefix.expand.rna";
#chmod 0666, "$results_dir/$prefix.expand.lca";

# move run_dir to stage_dir if on local
#if ($run_dir ne $stage_dir) {
#  system("mv $run_dir/*.out $stage_dir/.");
#  system("mv $run_dir/*.err $stage_dir/.");
#  system("rm -rf $run_dir") == 0 or fail($log, "$stage_name failed on job: $job_num, can not remove $run_dir");
#} else {
#  my @run_files = `ls $run_dir`;
#  chomp @run_files;
#  map { system("rm $run_dir/$_") } grep { $_ !~ /\.(out|err)$/ } @run_files;
#}

$log->info("Finished $stage_name on job: $job_num");

# update jobcache stage status
Pipeline::update_stage_info($job_num, $stage_name, "completed");

exit(0);

sub fail {
  my ($log, $message) = @_;
  Pipeline::update_stage_info($job_num, $stage_name, "error");
  $log->error($message);
  if ($run_dir ne $stage_dir) {
    system("mv $run_dir/* $stage_dir/.");
    system("rmdir $run_dir");
  }
  exit(1);
}
